---
- import_tasks: cluster.yml
  delegate_to: localhost

- import_tasks: volumes.yml
  delegate_to: localhost

- import_tasks: keys.yml
  delegate_to: localhost

- include_tasks: prepare.yml
  when: hostvars.localhost.servers_deployed.changed == True and state == "present"
