---
- name: Wait for any possibly running unattended upgrade to finish
  raw: 'systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true'

- name: Install requirements for managing host via ansible
  raw: "apt-get -y install python-simplejson"

- name: Disable MOTD to make root login faster
  file:
    path: /root/.hushlogin
    state: touch
