---
- name: Gather list of volumes and associated servers
  script: getvolumes-json.sh
  register: hcloud_storage

- name: Sort out list of volumes
  set_fact:
    hcloud_volumes: "{{ hcloud_volumes }} + [ '{{ item.0 }}_{{ item.1.mount }}' ]"
  loop: "{{ hcloud_storage.stdout|from_json|dictsort }}"
  vars:
    hcloud_volumes: []

# Currently creates/attaches volumes only to the first server of each
# profile (when volumes is defined)
- name: Create volumes
  script: "hcloud volume create --name {{ item.0.name[0] }}_{{ item.1.mount }} --size {{ item.1.size }} --server {{ item.0.name[0] }}"
  loop: "{{ query('subelements', nodes, 'volumes', {'skip_missing': True}) }}"
  when: >
    item.1 is defined and
    hcloud_volumes is not defined or
    item.0.name[0] ~ '_' ~ item.1.mount not in hcloud_volumes
  register: volumes_created
